# Generated by Django 5.2.2 on 2025-06-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_options_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_category', 'Can view category'), ('can_add_category', 'Can add category'), ('can_change_category', 'Can change category'), ('can_delete_category', 'Can delete category')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('can_view_collection', 'Can view collection'), ('can_add_collection', 'Can add collection'), ('can_change_collection', 'Can change collection'), ('can_delete_collection', 'Can delete collection')], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('can_view_inventory', 'Can view inventory'), ('can_add_inventory', 'Can add inventory'), ('can_change_inventory', 'Can change inventory'), ('can_delete_inventory', 'Can delete inventory')], 'verbose_name': 'Наличие', 'verbose_name_plural': 'Наличие'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'permissions': [('can_view_manufacturer', 'Can view manufacturer'), ('can_add_manufacturer', 'Can add manufacturer'), ('can_change_manufacturer', 'Can change manufacturer'), ('can_delete_manufacturer', 'Can delete manufacturer')], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_view_order', 'Can view order'), ('can_add_order', 'Can add order'), ('can_change_order', 'Can change order'), ('can_delete_order', 'Can delete order')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'permissions': [('can_view_orderitem', 'Can view order item'), ('can_add_orderitem', 'Can add order item'), ('can_change_orderitem', 'Can change order item'), ('can_delete_orderitem', 'Can delete order item')], 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product', 'Can view product'), ('can_add_product', 'Can add product'), ('can_change_product', 'Can change product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'permissions': [('can_view_promotion', 'Can view promotion'), ('can_add_promotion', 'Can add promotion'), ('can_change_promotion', 'Can change promotion'), ('can_delete_promotion', 'Can delete promotion')], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_view_review', 'Can view review'), ('can_add_review', 'Can add review'), ('can_change_review', 'Can change review'), ('can_delete_review', 'Can delete review')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('can_view_team', 'Can view team'), ('can_add_team', 'Can add team'), ('can_change_team', 'Can change team'), ('can_delete_team', 'Can delete team')], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
